PYENV_UV_REHASH_ROOT="${BASH_SOURCE[0]%/*}/uv-rehash"
PYENV_REHASH_COMMAND="${PYENV_COMMAND##*/}"

if [ -x "${PYENV_UV_REHASH_ROOT}/${PYENV_REHASH_COMMAND}" ]; then
  PYENV_COMMAND_PATH="${PYENV_UV_REHASH_ROOT}/${PYENV_REHASH_COMMAND}"
  PYENV_BIN_PATH="${PYENV_UV_REHASH_ROOT}"
  export PYENV_REHASH_REAL_COMMAND="${PYENV_REHASH_COMMAND}"
fi
