#!/usr/bin/env bash

set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Remove this directory from PATH to avoid infinite loops in `pyenv-which` (pyenv#146)
_PATH=":${PATH}:"
_HERE="$(dirname "${BASH_SOURCE[0]}")"
_PATH="${_PATH//:${_HERE}:/:}"
_PATH="${_PATH#:}"
_PATH="${_PATH%:}"
PATH="${_PATH}"

PYENV_COMMAND_PATH="$(pyenv-which "${PYENV_REHASH_REAL_COMMAND}")"
PYENV_BIN_PATH="${PYENV_COMMAND_PATH%/*}"

export PATH="${PYENV_BIN_PATH}:${PATH}"

STATUS=0
"$PYENV_COMMAND_PATH" "$@" || STATUS="$?"

# Run `pyenv-rehash` after a successful installation.
if [ "$STATUS" == "0" ]; then
  for uvarg in "$@"; do
    case ${uvarg} in
    "install" | "uninstall" ) pyenv-rehash ; break;;
    esac
  done
fi

exit "$STATUS"
